### ISSUE TITLE
hi north can I ask you a couple of things

### ISSUE THREAD

**Issue by Amstrong009** [thenorthstar/HaxBall-MineSweeperBot#2]
I noticed that you are one of the most respected people here that you passed a bot basketball a long time ago to some guys, well I needed to install it as a function that gives 3 points or 2 points depending on where you shoot in the field 4v4 futsal and not basketball but I know little about the coordinates of the maps, and related problems could you help me, sorry if I write in this section

if you have discord I can add you and talk better directly there.

**Comment by thenorthstar** [comment]
> I noticed that you are one of the most respected people here that you passed a bot basketball a long time ago to some guys, well I needed to install it as a function that gives 3 points or 2 points depending on where you shoot in the field 4v4 futsal and not basketball but I know little about the coordinates of the maps, and related problems could you help me, sorry if I write in this section
> 
> if you have discord I can add you and talk better directly there.

@Amstrong009 Hello bro. Frankly I have to say that I'm no longer helping people through GitHub or discord because of some people on these environments made me bored of helping the people. Just I can give you some idea to make you develop your bot yourself.

If your problem is about the geometry of the map, then I can say that both of these maps (basketball and futsal) have fundamentally similar geometries. Futsal one would require more coding because of its complexity with respect to the basketball one. If you have analyzed my code carefully, then you can code the futsal script easily.
